-- MySQL Script generated by MySQL Workbench
-- qua 25 jan 2023 09:37:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipoProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoProjeto` (
  `idtipoProjeto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idtipoProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projetos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projetos` (
  `idprojetos` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `imagem` BLOB NULL,
  `tipoProjeto_idtipoProjeto` INT NOT NULL,
  PRIMARY KEY (`idprojetos`),
  INDEX `fk_projetos_tipoProjeto_idx` (`tipoProjeto_idtipoProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_projetos_tipoProjeto`
    FOREIGN KEY (`tipoProjeto_idtipoProjeto`)
    REFERENCES `mydb`.`tipoProjeto` (`idtipoProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
